version: "3.3"

services:
    database:
        image: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 8003:5432

    server:
        build: .
        volumes:
            - ./:/app:Z
        environment: 
            DATABASE_URL: postgres://postgres:postgres@database:5432/postgres?sslmode=disable
        ports: 
            - 8000:8000
        depends_on:
            - database

