// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        int64          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Token     uuid.UUID      `json:"token"`
	Firstname sql.NullString `json:"firstname"`
	Lastname  sql.NullString `json:"lastname"`
	Phone     sql.NullInt64  `json:"phone"`
}
